name: Test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  liquidsoap-23:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4
      - run: |
          git clone https://github.com/savonet/liquidsoap -b rolling-release-v2.3.x
          opam pin --no-action --yes ./liquidsoap
          sudo apt-get update
          opam install --yes liquidsoap
      - run: |
          opam exec -- liquidsoap --version
          opam exec -- liquidsoap --build-config
          opam exec -- liquidsoap main.liq